version: "3.9"
services:
  my-portfolio:
    build:
      context: .
      dockerfile: Containerfile
    image: localhost/my-portfolio:latest
    container_name: my-portfolio
    restart: unless-stopped
    ports:
      - "3004:3004"
    environment:
      NODE_ENV: "production"
      PORT: "3004"
      NEXT_PUBLIC_STRAPI_URL: "https://strapi.cihuy-familly.my.id"
      STRAPI_PUBLIC_PROJECTS_ENDPOINT: "public-projects"
      STRAPI_CLOSE_PROJECTS_ENDPOINT: "close-projects"
      STRAPI_EXPERIENCES_ENDPOINT: "work-experiences"
      # STRAPI_API_TOKEN: "${STRAPI_API_TOKEN}"
      # STRAPI_API_TOKEN: "isi-token-jika-collection-private"
    healthcheck:
      test: ["CMD", "wget", "-qO", "-", "http://localhost:3004"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
